# Generated by Django 4.1.3 on 2022-11-24 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import seller.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, 'Прочее'), (1, 'Женский гардероб'), (2, 'Мужской гардероб'), (3, 'Детский гардероб'), (4, 'Детские товары'), (5, 'Хэндмейд'), (6, 'Телефоны и планшеты'), (7, 'Фото и видеокамеры'), (8, 'Компьютерная техника'), (9, 'ТВ, аудио, видео'), (10, 'Бытовая техника'), (11, 'Для дома и дачи'), (12, 'Стройматериалы и инструменты'), (13, 'Красота и здоровье'), (14, 'Спорт и отдых'), (15, 'Хобби и развлечения')], verbose_name='Категория')),
                ('condition', models.IntegerField(choices=[(0, 'БУ'), (1, 'Новое')], verbose_name='Состояние')),
                ('type_announcement', models.IntegerField(choices=[(0, 'Продаю свое'), (1, 'Приобрел на продажу'), (2, 'Магазин')], verbose_name='Тип объявления')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Цена')),
                ('description', models.CharField(max_length=3000, verbose_name='Описание')),
                ('sold', models.BooleanField(default=False, verbose_name='Продано')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='telegram username')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='phone number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementSaleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=seller.models._get_announcement_sale_image_filepath, verbose_name='Изображение')),
                ('announcement_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.announcementsale', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Изображение объявления',
                'verbose_name_plural': 'Изображения объявлений',
            },
        ),
        migrations.AddField(
            model_name='announcementsale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller', verbose_name='Продавец'),
        ),
    ]
