# Generated by Django 4.1.3 on 2022-11-26 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import seller.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(None, 'Не выбрано'), (0, 'Прочее'), (1, 'Женский гардероб'), (2, 'Мужской гардероб'), (3, 'Детский гардероб'), (4, 'Детские товары'), (5, 'Хэндмейд'), (6, 'Телефоны и планшеты'), (7, 'Фото и видеокамеры'), (8, 'Компьютерная техника'), (9, 'ТВ, аудио, видео'), (10, 'Бытовая техника'), (11, 'Для дома и дачи'), (12, 'Стройматериалы и инструменты'), (13, 'Красота и здоровье'), (14, 'Спорт и отдых'), (15, 'Хобби и развлечения')], verbose_name='категория')),
                ('condition', models.IntegerField(choices=[(None, 'Не выбрано'), (0, 'БУ'), (1, 'Новое')], verbose_name='состояние')),
                ('type_announcement', models.IntegerField(choices=[(None, 'Не выбрано'), (0, 'Продаю свое'), (1, 'Приобрел на продажу'), (2, 'Магазин')], verbose_name='тип объявления')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='цена')),
                ('description', models.CharField(max_length=3000, verbose_name='описание')),
                ('sold', models.BooleanField(default=False, verbose_name='продано')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=seller.models._get_announcement_sale_image_filepath, verbose_name='изображение')),
                ('announcement_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.announcement', verbose_name='объявление')),
            ],
            options={
                'verbose_name': 'изображение объявления',
                'verbose_name_plural': 'изображения объявлений',
            },
        ),
        migrations.RemoveField(
            model_name='announcementsaleimage',
            name='announcement_sale',
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'продавец', 'verbose_name_plural': 'продавцы'},
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='имя пользователя телеграм'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.DeleteModel(
            name='AnnouncementSale',
        ),
        migrations.DeleteModel(
            name='AnnouncementSaleImage',
        ),
        migrations.AddField(
            model_name='announcement',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller', verbose_name='продавец'),
        ),
    ]
