# Generated by Django 4.1.3 on 2022-11-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_announcement_announcementimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='latitude',
            field=models.FloatField(default=1, verbose_name='широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='longitude',
            field=models.FloatField(default=1, verbose_name='долгота'),
            preserve_default=False,
        ),
    ]
