# Generated by Django 4.1.3 on 2022-12-10 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_announcement_announcementimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller', verbose_name='продавец'),
        ),
    ]
