# Generated by Django 4.1.3 on 2022-12-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_announcement_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.seller', verbose_name='продавец'),
            preserve_default=False,
        ),
    ]
