# Generated by Django 4.1.3 on 2022-12-01 09:49

import django.core.validators
from django.db import migrations, models
import seller.models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_announcement_communication_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcementimage',
            old_name='announcement_sale',
            new_name='announcement',
        ),
        migrations.AlterField(
            model_name='announcementimage',
            name='image',
            field=models.ImageField(upload_to=seller.models._get_announcement_sale_image_filepath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='изображение'),
        ),
    ]
