# Generated by Django 4.1.3 on 2022-12-13 11:17

import announcement.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(None, 'Не выбрано'), (0, 'Прочее'), (1, 'Женский гардероб'), (2, 'Мужской гардероб'), (3, 'Детский гардероб'), (4, 'Детские товары'), (5, 'Хэндмейд'), (6, 'Телефоны и планшеты'), (7, 'Фото и видеокамеры'), (8, 'Компьютерная техника'), (9, 'ТВ, аудио, видео'), (10, 'Бытовая техника'), (11, 'Для дома и дачи'), (12, 'Стройматериалы и инструменты'), (13, 'Красота и здоровье'), (14, 'Спорт и отдых'), (15, 'Хобби и развлечения')], verbose_name='категория')),
                ('condition', models.IntegerField(choices=[(None, 'Не выбрано'), (0, 'БУ'), (1, 'Новое')], verbose_name='состояние')),
                ('type_announcement', models.IntegerField(choices=[(None, 'Не выбрано'), (0, 'Продаю свое'), (1, 'Приобрел на продажу'), (2, 'Магазин')], verbose_name='тип объявления')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=13, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='цена')),
                ('description', models.CharField(blank=True, max_length=3000, null=True, verbose_name='описание')),
                ('sold', models.BooleanField(default=False, verbose_name='продано')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='дата изменения')),
                ('communication_method', models.IntegerField(choices=[(0, 'email'), (1, 'telegram_username'), (2, 'phone_number')], default=0, verbose_name='способ связи')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller', verbose_name='продавец')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=announcement.models._get_announcement_sale_image_filepath, verbose_name='изображение')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement', verbose_name='объявление')),
            ],
            options={
                'verbose_name': 'изображение объявления',
                'verbose_name_plural': 'изображения объявлений',
            },
        ),
    ]
