# Generated by Django 4.1.3 on 2022-12-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='communication_method',
            field=models.IntegerField(choices=[(0, 'Адрес электронной почты'), (1, 'Имя пользователя телеграм'), (2, 'Номер телефона')], default=0, verbose_name='способ связи'),
        ),
    ]
