# Generated by Django 4.1.3 on 2023-01-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_alter_announcement_communication_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-date_created',), 'verbose_name': 'объявление', 'verbose_name_plural': 'объявления'},
        ),
    ]
