# Generated by Django 4.1.3 on 2023-01-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(unique=True, verbose_name='идентификатор пользователя телеграм')),
                ('notifications_enabled', models.BooleanField(default=False, verbose_name='статус уведомлений')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller', verbose_name='продавец')),
            ],
            options={
                'verbose_name': 'пользователь телеграм',
                'verbose_name_plural': 'пользователи телеграм',
            },
        ),
    ]
