# Generated by Django 4.1.3 on 2023-01-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertelegram',
            name='user',
        ),
        migrations.AddField(
            model_name='usertelegram',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.seller', verbose_name='продавец'),
            preserve_default=False,
        ),
    ]
