# Generated by Django 4.1.3 on 2023-01-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_password_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_password_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='последнее обновление пароля'),
        ),
    ]
